services:
  db:
    image: postgres:15
    container_name: avito_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  pipeline:
    build: .
    container_name: avito-realestate
    tty: true
    stdin_open: true
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

volumes:
  postgres_data: