@echo off
echo Rebuilding Docker...
docker-compose up -d --build
echo Initializing Database...
type db_init\init.sql | docker-compose exec -T db psql -U admin -d avito_warehouse
echo Starting Pipeline...
docker exec -it avito-realestate python3 run_pipeline.py
pause